name: frontendCDworkflow
on:
  workflow_dispatch:
    paths:
      -'frontend/**'
    branches:       
      - main
        
  pull_request:
    paths:
      -'frontend/**'  
    branches: 
      - main


jobs:
  deploy_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Generate deployment package
      run: |
        zip -r application.zip . -x '*.git*'

    - name: 
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
        application_name: my-node-app
        environment_name: my-node-app-pr-${{ github.event.pull_request.number }}
        version_label: version-${{ github.run_number }}
        region: us-east-1
        deployment_package: application.zip